### ISSUE TITLE
Review Checklist

### ISSUE THREAD

**Issue by davidmarkclements** [nodejs-certified-developer/certification#25]
Please copy the following checklist, paste it into the PR thread and complete when reviewing item PR's:

```
- [ ] check for typos
- [ ] comprehension – does it make sense, what about to non-native English speakers?
- [ ] files structure - do they match the meta data in the questions markdown doc
- [ ] in the markdown doc, is the goal aligned with task 
- [ ] in the markdown doc, are the correct files hidden 
- [ ] ensure the phase is completed
- [ ] check that the variant number matches the item code
- [ ] assertion code - does it cover all cases/approaches
- [ ] package.json - any stray deps, correctly named etc.
- [ ] is the description correctly duplicated in project folder (IMPORTANT)
- [ ] do supplied answers correctly validate IN NODE 10
- [ ] is the question still relevant in a Node 10 context
```

**Comment by vvscode** [comment]
don't you want put it to issue template?

**Comment by Horaddrim** [comment]
I think this checklist is for the guy who will review the PR,  @vvscode, but I think we have to work on an issue template ASAP
